Create Releases “2022-07-06-june-2022”
GSA/search-gov-website pull request #133
Opened 2022-07-06 19:29 UTC by amanifarooque

Automatically generated by Netlify CMS

2022-07-12 19:43 UTC, amanifarooque commented
Link to release notes: https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.app.cloud.gov/preview/gsa/search-gov-website/cms/releases/2022-07-06-june-2022/about/updates/releases/june-2022.html

2022-07-12 19:45 UTC, amanifarooque commented
@dawnpm - I can't add Rob as a reviewer to this PR to review as dev lead representative. Can we adjust the permissions to whatever group makes sense so he can review?

2022-07-18 15:13 UTC, MyNameIsMissing requested changes
Small item I would change if not terribly inconvenient to do so.

2022-07-18 15:13 UTC, MyNameIsMissing commented on _releases/2022-07-06-june-2022.md
> +* **ElasticSearch Upgrade**: We’ve continued progress on upgrading our ElasticSearch version across our system.
The apostrophe here and the one above don't match.  Not sure why.  I recommend making them consistent.  There is a small potential for some future system to choke on the difference.  The second one is probably from copy-paste from MS Word I'm guessing.

2022-07-18 19:15 UTC, MyNameIsMissing submitted a review, later dismissed
LGTM

2022-07-19 15:58 UTC, dawnpm commented
@amanifarooque Can we do a block indent of the sitemap examples, so that they align with the bullet point? I was confused by the alignment.

2022-07-20 21:03 UTC, merged