Add Q4 Roadmap
GSA/search-gov-website pull request #134
Opened 2022-07-19 15:06 UTC by amanifarooque

## PR Checklist
- [x] Test Federalist Preview link for your branch for functionality - make sure all links and buttons work, javascript works as intended, and updates display as expected
- [x] Conduct a HemingwayApp review of the content for plain language. Request plain language review in #helpwanted if needed before merging this PR
- Conduct a Lighthouse Audit via Chrome Developer Tools. Identify any issues that must be addressed before merging, and fix - N/A
- [x] Ensure no non-public information is published in the commit messages

2022-07-19 15:41 UTC, dawnpm requested changes

2022-07-19 17:07 UTC, amanifarooque commented on about/updates/roadmap/FY22Q3-roadmap.md
> +* **New Developer Onboarding**
Updated, re-requesting review

2022-07-20 21:13 UTC, amanifarooque commented
@dawnpm I pushed an update, are you OK to approve based off of this local screenshot so I can merge, rather than waiting the 6 min for the preview to build? 
<img width="793" alt="image" src="https://user-images.githubusercontent.com/7243053/180083308-d4eec015-5f6c-4791-a348-d07f555d0aae.png">

2022-07-20 21:15 UTC, dawnpm approved these changes

2022-07-20 21:17 UTC, dawnpm commented
Go ahead and merge, thanks.

2022-07-20 21:17 UTC, merged