Create 2023-10-24-september-2023.md
GSA/search-gov-website pull request #221
Opened 2023-10-24 17:24 UTC by arantxarecio

## PR Checklist
- [x ] Test [Cloud.gov Pages preview](https://pages.cloud.gov/sites/764/builds) for your branch for functionality - make sure all links and buttons work, javascript works as intended, and updates display as expected
  - Preview link: 
- [ x] Conduct a [HemingwayApp](https://hemingwayapp.com/) review of the content for plain language. Request plain language review in #helpwanted if needed before merging this PR
- [ x] Conduct a Lighthouse Audit via Chrome Developer Tools. Identify any issues that must be addressed before merging, and fix
- [ x] Ensure no non-public information is published in the commit messages

2023-10-24 17:25 UTC, arantxarecio commented
Preview: https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.sites.pages.cloud.gov/preview/gsa/search-gov-website/arantxarecio-patch-1/about/updates/newsletters/september-2023.html

2023-10-24 17:53 UTC, dawnpm commented on _newsletters/2023-10-24-september-2023.md
> +As previously announced, our faceted search capability is now available for our customers using API results, and it will soon become available to those customers using hosted results. If you are inte
the email link needs to be 
[search@gsa.gov](mailto:search@gsa.gov)

Can you update in both places, here and below, please?

2023-10-24 17:54 UTC, dawnpm requested changes
Looks pretty good, one functional change we need to make in two places. thanks.

2023-10-26 15:51 UTC, dawnpm commented on _newsletters/2023-10-24-september-2023.md
> +As previously announced, our faceted search capability is now available for our customers using API results, and it will soon become available to those customers using hosted results. If you are inte
`[search@gsa.gov](mailto:search@gsa.gov)`

2023-10-26 17:55 UTC, dawnpm approved these changes

2023-10-26 17:57 UTC, merged