Add FY22 Q4 Roadmap
GSA/search-gov-website pull request #87
Opened 2022-01-24 18:34 UTC by amanifarooque

## PR Checklist
- [ ] Test Federalist Preview link for your branch for functionality - make sure all links and buttons work, javascript works as intended, and updates display as expected
- [ ] Conduct a HemingwayApp review of the content for plain language. Request plain language review in #helpwanted if needed before merging this PR
- [ ] Conduct a Lighthouse Audit via Chrome Developer Tools. Identify any issues that must be addressed before merging, and fix
- [ ] Ensure no non-public information is published in the commit messages

2022-01-24 18:55 UTC, amanifarooque commented
Roadmap URL: https://cg-a72b65a7-73f0-4859-a1d7-dc953cf6ade8.app.cloud.gov/preview/gsa/search-gov-website/afarooque/roadmap-updates/about/updates/roadmap/

2022-01-25 20:04 UTC, dawnpm commented on about/updates/roadmap/index.md
> +  * We will continue work on the ElasticSearch upgrade to keep them up-to-date.
them?

2022-01-25 20:06 UTC, dawnpm commented on about/updates/roadmap/index.md
> +* **Search.gov website redesign - performance monitoring**
I'm on the fence for including this, leaning towards removing it, since it's just admin team-side.

2022-01-25 20:06 UTC, dawnpm commented on about/updates/roadmap/index.md
> +* **Faceted Search: User Discovery**
awesome, thanks for including

2022-01-25 20:08 UTC, dawnpm requested changes
some praise, one philosophical question, and one language tweak.

2022-01-25 21:34 UTC, merged